services:
  mongo:
    image: mongo:7
    container_name: ryde-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: rydeapi

  ryde-api:
    build: .
    container_name: ryde-api
    ports:
      - "${PORT:-8080}:8080"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://mongo:27017
    restart: unless-stopped

volumes:
  mongo-data:
